version: '2'
services:
    gateway-app:
        image: gateway
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8080'
    gateway-postgresql:
        image: 'postgres:10.4'
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    jhipsterblackbelt-app:
        image: jhipsterblackbelt
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATA_MONGODB_URI=mongodb://jhipsterblackbelt-mongodb:27017'
            - SPRING_DATA_MONGODB_DATABASE=jhipsterBlackbelt
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    jhipsterblackbelt-mongodb:
        image: 'mongo:4.0.2'
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
